name: atento
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  intl: ^0.20.2
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/aceitar/
    - assets/sounds/correr/
    - assets/sounds/doze/
    - assets/sounds/nove/
    - assets/sounds/seis/
    - assets/sounds/truco/
    - assets/images/
